Upgrade versions and add extra content
OpenDataServices/sphinx-base pull request #10
Opened 2023-01-11 11:08 UTC by radix0000

Has been upgraded as far as is possible (while sticking with sphinx-rtd-theme). Versions of important packages are:

sphinx==5.3.0
sphinx-rtd-theme==1.1.1
myst-parser==0.18.1
docutils==0.17.1

Kitchen sink and sphinx examples for tables etc. added.

2023-01-17 18:44 UTC, Bjwebb requested changes

2023-01-17 18:44 UTC, Bjwebb commented on docs/examples/admonitions.rst
> +    }
This css doesn't seem to be used anywhere, so the admonition at the bottom doesn't get rendered correctly https://sphinx-base.readthedocs.io/en/upgrade_to_latest_version/examples/admonitions.html

2023-01-17 18:46 UTC, Bjwebb commented
I've spotted something that seems to be broken with the examples.

I'm happy with all the version updates though, so do make those same changes to [openreferral/specification](https://github.com/openreferral/specification/).

2023-01-18 16:46 UTC, radix0000 commented
Have added back missing CSS file, and custom admonition at bottom should now be rendering correctly.

2023-01-19 17:44 UTC, Bjwebb approved these changes
Approving now because admonition is now clearly styled. 

The logo looks to be slightly mangled on my screen though:
![Screenshot from 2023-01-19 17-43-46](https://user-images.githubusercontent.com/634/213520318-564464c6-fd28-4aff-a798-6646f6a8f6e3.png)

2023-01-25 10:54 UTC, merged